"""add route indexes

Revision ID: 62cc1e8ffa7b
Revises: 8b59d0f865eb
Create Date: 2026-02-19 14:18:19.039899

"""
from typing import Sequence, Union
from sqlalchemy import text
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '62cc1e8ffa7b'
down_revision: Union[str, Sequence[str], None] = '8b59d0f865eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    

    conn = op.get_bind()
    conn.execute(text("DROP INDEX IF EXISTS ix_scans_day"))
   
   # op.drop_index(op.f('ix_scans_gb_number'), table_name='scans')
   # op.drop_index(op.f('ix_scans_route'), table_name='scans')
   # op.drop_index(op.f('ix_scans_user'), table_name='scans')
   # op.create_index('ix_scans_day_route', 'scans', ['day', 'route'], unique=False)
   # op.create_index('ix_scans_day_route_ts', 'scans', ['day', 'route', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_index('ix_scans_day_route_ts', table_name='scans')
   # op.drop_index('ix_scans_day_route', table_name='scans')
   # op.create_index(op.f('ix_scans_user'), 'scans', ['user'], unique=False)
   # op.create_index(op.f('ix_scans_route'), 'scans', ['route'], unique=False)
   # op.create_index(op.f('ix_scans_gb_number'), 'scans', ['gb_number'], unique=False)
   # op.create_index(op.f('ix_scans_day'), 'scans', ['day'], unique=False)
    # ### end Alembic commands ###
