"""add route_status table

Revision ID: 75c70ce58945
Revises: 984dde36213f
Create Date: 2026-02-20 07:28:49.115243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c70ce58945'
down_revision: Union[str, Sequence[str], None] = '984dde36213f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('route', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')", name='ck_route_status_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'route', name='uq_route_status_day_route')
    )
    op.create_index('ix_route_status_day_route', 'route_status', ['day', 'route'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_route_status_day_route', table_name='route_status')
    op.drop_table('route_status')
    # ### end Alembic commands ###
