"""add expected items

Revision ID: 984dde36213f
Revises: 6d8e192aec45
Create Date: 2026-02-20 05:11:24.789615

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '984dde36213f'
down_revision: Union[str, Sequence[str], None] = '6d8e192aec45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
