"""add expected items

Revision ID: aab9de4d3020
Revises: 62cc1e8ffa7b
Create Date: 2026-02-20 01:21:54.492813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab9de4d3020'
down_revision: Union[str, Sequence[str], None] = '62cc1e8ffa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('route', sa.Integer(), nullable=False),
    sa.Column('gb_number', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'route', 'gb_number', name='uq_expected_day_route_gb')
    )
    op.create_index('ix_expected_day_route', 'expected_items', ['day', 'route'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expected_day_route', table_name='expected_items')
    op.drop_table('expected_items')
    # ### end Alembic commands ###
