"""add route_status table

Revision ID: dc15065fabb5
Revises: 75c70ce58945
Create Date: 2026-02-20 07:30:23.673810

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'dc15065fabb5'
down_revision: Union[str, Sequence[str], None] = '75c70ce58945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
